// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLrK5rcgFhUW69sc4WrvlPedjAhPVyBck',
    appId: '1:230620622122:web:11baf39802aee0fe924253',
    messagingSenderId: '230620622122',
    projectId: 'sjieg-96601',
    authDomain: 'sjieg-96601.firebaseapp.com',
    storageBucket: 'sjieg-96601.appspot.com',
    measurementId: 'G-NFKG8GP1ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Sh0Af2EmVCtIz1h2-qt1n8aF6EXXqD8',
    appId: '1:230620622122:android:66f1ab82fd31805d924253',
    messagingSenderId: '230620622122',
    projectId: 'sjieg-96601',
    storageBucket: 'sjieg-96601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKecE4XQrj7JWs7kbjFTIb6FfCQ5fFk6Q',
    appId: '1:230620622122:ios:1ff29faf507910bb924253',
    messagingSenderId: '230620622122',
    projectId: 'sjieg-96601',
    storageBucket: 'sjieg-96601.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKecE4XQrj7JWs7kbjFTIb6FfCQ5fFk6Q',
    appId: '1:230620622122:ios:1ff29faf507910bb924253',
    messagingSenderId: '230620622122',
    projectId: 'sjieg-96601',
    storageBucket: 'sjieg-96601.appspot.com',
    iosBundleId: 'com.example.untitled',
  );
}
